### ISSUE TITLE
Create a markdown checklist template for pull requests

### ISSUE THREAD

**Issue by svarona** [pha4ge/public-health-pipeline-best-practices#2]
When a group wants to include their pipeline in PHA4GE, they must create a PR requesting the review of their pipeline by the working group. For these PRs there will be a checklist template where the group can check if it meets all the PHA4GE best practice/standards, and provide links to facilitate the review by the working group.

These PR templates should be a `.github/PULL_REQUEST_TEMPLATE/pipeline_checklist_template.md` file. In the `PULL_REQUEST_TEMPLATE` folder, we could store two types of templates:
- Pipeline checklist templates (for groups to include their pipelines in PHA4GE)
- Documents modification PR (to modify of contribute to the main documentation of the repo)

**Comment by svarona** [comment]
# `pipeline_checklist_template.md` file suggestion

## Checklist to include a pipeline inside the PHA4GE Public Health Bioinformatics Pipelines's Best Practices

1. _**Publicly-Accessible Repository.**_
    - *Is the source code for this pipeline available at a publicly-accessible repository URL?*
    - *To adhere to this best practice* you need to host the bioinformatics pipeline on an open code repository platform.
    - [ ] **Provide publicly-accessible repository URL**: `                         `
2. _**Open-Source License.**_
    - *Does the repository contain a plain-text LICENSE file with the contents of an OSI-approved software license?*
    - *To adhere to this best practice* choose an open-source license (e.g., MIT) for the pipeline, providing legal permissions for users to modify and share the code.
    - [ ] **Specify the open-source license of your repo**: `                         `
3. _**Semantic Versioning of Stable Releases**_
    - *Are stable releases that follow semantic versioning of the pipeline available for implementation in public health laboratories?*
    - *To adhere to this best practice implement semantic versioning (e.g., MAJOR.MINOR.PATCH).*
    - [ ] **Please enter current approved version**: `                         `
4. _**Workflow Management System**_
    - *Does the pipeline utilize a workflow management system for its development and execution?*
    - *To adhere to this best practice* choose a workflow management system that supports scalability, is compatible with common bioinformatics tools, and integrates easily with existing infrastructure. Document the workflow configuration and dependencies clearly.
    - [ ] **Specify the workflow management system used**: `                         `
5. _**Containerized/Packaged Software**_
    - *Does the pipeline utilize containerized software (e.g. Docker) or packaging (e.g. conda) to enhance interoperable pipeline distribution?*
    - *To adhere this best practice* implement pipeline components within software containers or distribute them as Conda packages. Use of containerized/packaged software should be clearly documented.
    - [ ] **Specify the Containerized/Packaged Software used**: `                         `
6. _**Common File Formats**_
    - *Does the pipeline accept as input and generate as output common file format utilized in public health pathogen genomics?*
    - *To adhere to this best practice* the pipeline should accept as input and generate as output common file formats utilized in public health pathogen genomics, enhancing interoperability and data exchange between different tools and platforms.
    - [ ] **Provide an URL to the documentation where you specify the common file formats used in your pipeline**: `                         `
7. _**Software Testing**_
    - *Are there automated and/or manual tests described so that the functionality of the pipeline can be assessed?*
    - *To adhere to this best practice* provide a description of both automated and/or manual tests that assess the functionality of the pipeline, ensuring reliability and accuracy.
    - [ ] **Provide an URL to the tests or provide a description of them**: `                         `
8. _**Benchmark/Validation Datasets**_
    - *Is there a publicly available set of inputs with known outputs that can be used to test successful installation and benchmark against other tools?*
    - *To adhere to this best practice* include a benchmark or validation dataset for the public health bioinformatics pipeline to promote transparency and consistency in the evaluation and comparison of different tools.
    - [ ] **Provide an URL to the benchmark or validation dataset**: `                         `
9. _**Reference Data Requirements**_
    - *Are required reference data and/or databases clearly documented, publicly accessible, and maintained?*
    - *To adhere to this best practice* the required reference data and/or databases for public health bioinformatics pipeline should be clearly documented, publicly accessible, and maintained. If an external reference database is required, it should also adhere to standards such as static versioning, open-access, and clear instructions for installation/access. Clearly document aspects of the database, such as the schema, table structure, and stored procedures, in a format suitable for users, such as technical documentation, user guides, and reference manuals.
    - [ ] **Provide an URL to the documentation where you specify the reference data requirements**: `                         `
10. _**Pipeline Documentation**_
    - *Is the pipeline documentation clearly written and publicly accessible?*
    - *To adhere to this best practice and verify adherence to this best practice* refer to the documentation practices listed below; all pipeline documentation practices should be met.
    1. **Contribution, Authorship, and Verified Point of Contact**
        - *Does the full list of authors seem appropriate and include a verified point of contact?*
        - *To adhere to this documentation practice* clearly list authorship and credit for the bioinformatics tool, acknowledging individual contributions and following the CRedIT system for appropriate recognition based on specific contributions.
        - [ ] **Provide an URL to the documentation where you specify the authorship and credit**: `                         `
        - [ ] **Please enter an e-mail address**: `                         `
    2. **Conflict of Interest Statement**
        - *Have all potential conflicts of interest been disclosed?*
        - *To adhere to this documentation practice* authors of public health bioinformatics pipeline should transparently disclose any potential conflicts of interest, such as commercial, personal, political, or religious affiliations, to promote transparency and integrity in scientific research.
        - [ ] **Provide an URL to the documentation where you resolve all potential conflicts of interest**: `                         `
     3. **Pipeline Maintenance Statement**
        - *Have the authors provided documentation regarding the intent to maintain the pipeline?*
        - *To adhere to this documentation practice* authors must include a detailed statement regarding the pipeline's future upkeep, covering aspects such as update schedules, user support mechanisms, and funding or community support strategies.
        - [ ] **Provide an URL to the documentation where you specify the intent to maintain the pipeline**: `                         `
    4. **Community Guidelines for Contribution and Support**
        - *Are there clear guidelines for third parties wishing to 1) contribute to the pipeline 2) report issues or problems with the pipeline and 3) seek support?*
        - *To adhere to this documentation practice* include community guidelines for contribution and support on the code repository where the pipeline is made available. Ensure that community guidelines foster an environment of shared knowledge and expertise, enabling individuals to contribute feedback, report issues, and actively participate in the improvement and sustainability of essential tools and resources.
        - [ ] **Provide an URL to the documentation where you specify the community guidelines for contribution and support**: `                         `
     5. **Statement of Need with Respect to Public Health Pathogen Genomics**
        - *Have the authors clearly stated the challenges in public health pathogen genomics that this pipeline aims to address?*
        - *To adhere to this documentation practice* clearly state the significance and relevance of public health bioinformatics pipeline and explain how the tool differs from existing ones and/or improves established methods.
        - [ ] **Provide an URL to the documentation where you specify the statement of need**: `                         `
     6. **Pipeline Functionality**
        - *Has the function of this software as it pertains to public health bioinformatics been clearly articulated?*
        - *To adhere to this documentation practice* clearly indicate the function, intended use, and limitations of the software.
        - [ ] **Provide an URL to the documentation where you specify the pipeline functionality**: `                         `
      7. **Documentation for Local Installation and/or Remote Access (e.g. Web Server or Galaxy/Terra Workflow)**
        - *Does installation and/or access to the pipeline proceed as outlined in the documentation?*
        - *To adhere to this documentation practice* authors of public health bioinformatics pipeline should offer clear local installation and/or remote access instructions, ensuring a streamlined user experience and facilitating efficient deployment of essential tools. Installation instructions should include detailed configuration settings with clear expected outcomes, step-by-step lists, and verification methods for successful installation, along with troubleshooting guidance for common issues. If resources are available via a web application (e.g., Galaxy or Terra.Bio), clear instructions on how to access and utilize the pipeline through the web application should be provided.
        - [ ] **Provide an URL to the documentation where you specify the installation and/or remote access instructions**: `                         `
     8. **Example Usage**
        - *Do the authors include examples of how to use this pipeline?*
        - *To adhere to this documentation practice* provide practical guidance by documenting an example usage for public health bioinformatics pipeline, offering researchers clear instructions on how to effectively apply the tool in real-world scenarios. Ensure that the example usage enhances researchers' understanding of the pipeline, facilitating successful integration into research workflows and maximizing its utility for advancing public health outcomes.
        - [ ] **Provide an URL to the documentation where you specify the example of usage**: `                         `
